services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:81
    depends_on:
      - node
      - front
    networks:
      - app-network

  node:
    build:
      context: ./Docker-back
    volumes:
      - ./Docker-back:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - app-network

  front:
    build:
      context: ./Docker-front
    volumes:
      - ./Docker-front:/usr/src/app
    ports:
      - 8080:8080
    networks:
      - app-network
      

networks:
  app-network:
